apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: youtube-accounts
  name: youtube-accounts
spec:
  ports:
    - name: "5173"
      port: 5173
      targetPort: 80
  selector:
    io.kompose.service: youtube-accounts
