apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: youtube-admin
  name: youtube-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: youtube-admin
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: youtube-admin
    spec:
      containers:
        - image: frontend-youtube-admin:latest
          name: youtube-admin
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Never
      restartPolicy: Always
