apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: data-protection
  name: data-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
