version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: YouTube.WebAPI/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - S3Storage_AccessKey=minioadmin
      - S3Storage_SecretKey=minioadmin
      - S3Storage_Endpoint=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=defaultbucket
      - REDIS_CONNECTION_STRING=redis:6379
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8080:8080"
    networks:
      - youtube_network
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys
    
  db:
    image: postgres:16
    container_name: Youtube.PostgresSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: youtube
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - youtube_network

  redis:
    container_name: Youtube.Redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - youtube_network

  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - youtube_network

volumes:
  db_data:
  minio_data:
  data_protection:

networks:
  youtube_network:
    driver: bridge
