services:
  webapi:
    build:
      context: .
      dockerfile: YouTube.WebAPI/Dockerfile 
    container_name: Youtube.WebApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - S3Storage_AccessKey=minioadmin
      - S3Storage_SecretKey=minioadmin
      - S3Storage_Endpoint=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - REDIS_CONNECTION_STRING=redis:6379
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=youtube-payments
      - PaymentService__GrpcEndpoint=http://payment:5001
    depends_on:
      db:
        condition: service_healthy
      payment_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      redis:
    ports:
      - "8080:8080"
    networks:
      - youtube_network
    restart: always
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys

  busapi:
    build:
      context: .
      dockerfile: YouTube.BusAPI/Dockerfile 
    container_name: Youtube.BusApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitOptions_Username=guest
      - RabbitOptions_Password=guest
      - RabbitOptions_Hostname=rabbit
      - REDIS_CONNECTION_STRING=redis:6379
    depends_on:
      db:
        condition: service_healthy
      payment_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      redis:
    ports:
      - "8090:8090"
    networks:
      - youtube_network
    restart: always
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys

  payment:
    build:
      context: .
      dockerfile: YouTube.Payment/Dockerfile
    container_name: Youtube.Payment
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=youtube-payments
      - ASPNETCORE_URLS=http://+:8085  
    depends_on:
      db:
        condition: service_healthy
      payment_db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      redis:
    ports:
      - "8085:8085"  
    networks:
      - youtube_network
    restart: always

  db:
    image: postgres:16
    container_name: Youtube.Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: youtube
      POSTGRES_DB: youtube
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - youtube_network
    restart: always
    healthcheck:      
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s     
      retries: 5

  payment-db:
    image: postgres:16
    container_name: Youtube.PaymentDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: youtube-payment
    volumes:
      - payment_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - youtube_network
    restart: always
    healthcheck:      
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s     
      retries: 5

  redis:
    container_name: Youtube.Redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - youtube_network
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: Youtube.MinioS3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    networks:
      - youtube_network

  rabbit: 
    image: rabbitmq:3-management
    container_name: Youtube.RabbitMq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - youtube_network
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

volumes:
  db_data:
  minio_data:
  data_protection:
  payment_data:

networks:
  youtube_network:
    driver: bridge