global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'webapi'
    static_configs:
      - targets: ['webapi:8080'] 

  # - job_name: 'rabbitmq'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['rabbit:15692']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187'] 
    metrics_path: '/metrics'


  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:9121']